
# aliases.yml
# ---
apiVersion: v1
kind: Service
metadata:
  name: redis              # <-- alias name that apps expect (redis)
spec:
  selector:
    name: redis-pod        # <-- MUST match your redis Pod labels
    app: demo-redis-app
  ports:
    - port: 6379
      targetPort: 6379

# ---
apiVersion: v1
kind: Service
metadata:
  name: db                 # <-- alias name that apps expect (db)
spec:
  selector:
    name: postgres-pod     # <-- MUST match your postgres Pod labels
    app: demo-postgres-app
  ports:
    - port: 5432
      targetPort: 5432
