apiVersion: v1
kind: Pod
metadata: 
  name: result-app-pod
  labels:
    name: result-app-pod
    app: demo-result-app

spec:
  containers:
  - name: result-app 
    image: dockersamples/examplevotingapp_result
    ports:
     - containerPort: 80
    resources:
      requests:
        cpu: "150m"
        memory: "192Mi"
      limits:
        cpu: "300m"
        memory: "256Mi"
    env:
    - name: POSTGRES_HOST
      value: "db-service"
    - name: POSTGRES_PORT
      value: "5432"
    - name: POSTGRES_USER
      value: "postgres"
    - name: POSTGRES_PASSWORD
      value: "Naseem@123"
    - name: POSTGRES_DB
      value: "myDb"

