apiVersion: v1
kind: Pod
metadata: 
 name: voting-app-pod
 labels:
  name: voting-app-pod
  app: demo-voting-app
spec:
 containers:
 - name: voting-app
   image: dockersamples/examplevotingapp_vote
   ports:
   - containerPort: 80
   env:
    - name: REDIS_HOST
      value: "redis-service"
    - name: REDIS_PORT
      value: "6379"
