apiVersion: v1
kind: Pod
metadata: 
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: demo-worker-app

spec: 
  containers: 
  - name: worker-app
    image: dockersamples/examplevotingapp_worker
    resources:
      requests:
        cpu: "150m"
        memory: "128Mi"
      limits:
        cpu: "300m"
        memory: "256Mi"


