apiVersion: v1
kind: Pod
metadata: 
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: demo-worker-app

spec: 
  containers: 
  - name: worker-app
    image: dockersamples/examplevotingapp_worker
    resources:
      requests:
        cpu: "150m"
        memory: "128Mi"
      limits:
        cpu: "300m"
        memory: "256Mi"
    env:
      - name: REDIS_HOST
        value: "redis-service"
      - name: REDIS_PORT
        value: "6379"
      - name: POSTGRES_HOST
        value: "db-service"
      - name: POSTGRES_PORT
        value: "5432"
      - name: POSTGRES_USER
        value: "postgres"
      - name: POSTGRES_PASSWORD
        value: "Naseem@123"
      - name: POSTGRES_DB
        value: "myDb"



